[tool.poetry]
name = "example-pkg3"
version = "0.1.0"
description = ""
authors = ["Gustavo Albino <gustavo@gr4vy.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mypy = "^1.6.1"
aiohttp = "^3.8.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
