[tool.poetry]
name = "renovate-test"
version = "0.1.0"
description = ""
authors = ["Gustavo Albino <gustavo@radhark.tech"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"
aiohttp = "^3.8.1"
shed = "^2023.5.0"
mypy = "^1.6.1"