[tool.poetry]
name = "renovate-test"
version = "0.1.0"
description = ""
authors = ["Gustavo Albino <gustavo@radhark.tech"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
aiohttp = "3.10.10"
shed = "2023.5.1"
mypy = "1.6.1"