[tool.poetry]
name = "example-pkg"
version = "0.1.0"
description = ""
authors = ["Gustavo Albino <gustavo@gr4vy.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "3.10.10"
shed = "2023.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
