name: Renovate
on: push
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}